---
resources:
  - name: pipeline-src
    type: git
    source:
      uri: https://github.com/primesoftsbulusu/elasticbeanstalk-concourse-pipeline.git
      branch: master

  - name: demo-app-src
    type: git
    source:
      uri: https://github.com/primesoftsbulusu/elasticbeanstalk-demo-app.git
      branch: master
  - name: demo-app-artifact
    type: s3
    source:
      bucket: dev-app-ops
      region_name: us-east-2
      versioned_file: demo-app.jar
      access_key_id: ((AWS-KEY)) 
      secret_access_key: ((AWS-SECRET))


jobs:
  - name: build-demo-app
    build_logs_to_retain: 30
    plan:
      - aggregate:
        - get: pipeline-src
        - get: demo-app-src
          trigger: true
      - task: build
        file: pipeline-src/tasks/build/build.yml
      - put: demo-app-artifact
        params:
          file: build/demo-app.jar
          name: demo-app.jar
  - name: deploy-demo-app
    serial: true
    plan:
      - aggregate:
        - get: pipeline-src
        - get: demo-app-artifact
          passed:
            - build-demo-app
          trigger: true
      - task: deploy
        file: pipeline-src/tasks/deploy/deploy.yml
        params:
          APPLICATION_NAME: demo-app
          ENVIRONMENT_NAME: demo-app-env
          CNAME: demo-app-env
          AWS_ACCESS_KEY_ID: ((AWS-KEY))
          AWS_SECRET_ACCESS_KEY: ((AWS-SECRET))

groups:
  - name: demo-app
    jobs:
      - build-demo-app
      - deploy-demo-app
